services:
    runet_id.api_client.model_reconstructor:
        class: RunetId\ApiClient\ModelReconstructor
        arguments:
            - []

    runet_id.api_client.cache.file:
        class: RunetId\ApiClientBundle\Cache\FileCache
        arguments:
            - []
            - "@filesystem"

    runet_id.api_client.container:
        class: RunetId\ApiClientBundle\ApiClientContainer
        arguments:
            - []
            - "@runet_id.api_client.model_reconstructor"
            - ~

    runet_id.api_client.listener.api_user_loader:
        class: RunetId\ApiClientBundle\EventListener\ApiUserLoader
        arguments:
            - "@=service('runet_id.api_client.container').get(parameter('runet_id.api_client.default_credentials_name'))"
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    runet_id.api_client.auth_controller:
        class: RunetId\ApiClientBundle\Controller\AuthController
        arguments:
            - "@templating"
