services:
    runet_id.api_client.model_reconstructor:
        class: RunetId\ApiClient\ModelReconstructor
        arguments:
            - []

    runet_id.api_client.cache.file:
        class: RunetId\ApiClientBundle\Cache\FileCache
        arguments:
            - []
            - "@filesystem"

    runet_id.api_client.container:
        class: RunetId\ApiClientBundle\ApiClientContainer
        arguments:
            - []
            - "@runet_id.api_client.model_reconstructor"
            - ~

    runet_id.api_client.twig.api_extension:
        class: RunetId\ApiClientBundle\Twig\ApiExtension
        public: false
        tags:
            - { name: twig.extension }
